// https://de.wikipedia.org/wiki/I_Ging
// https://github.com/jesshewitt/i-ching/blob/main/site/data/hexagrams.js
// https://de.wikipedia.org/wiki/Unicodeblock_I-Ging-Hexagramme

export const HEXAGRAM = [
  { sequence: '111111', number: 1, meaning_de: 'Das Schöpferische', sign: '乾', unicode: '䷀' },
  { sequence: '000000', number: 2, meaning_de: 'Das Empfangende', sign: '坤', unicode: '䷁' },
  { sequence: '100010', number: 3, meaning_de: 'Die Anfangsschwierigkeit', sign: '屯', unicode: '䷂' },
  { sequence: '010001', number: 4, meaning_de: 'Die Jugendtorheit', sign: '蒙', unicode: '䷃' },
  { sequence: '111010', number: 5, meaning_de: 'Das Warten', sign: '需', unicode: '䷄' },
  { sequence: '010111', number: 6, meaning_de: 'Der Streit', sign: '訟', unicode: '䷅' },
  { sequence: '010000', number: 7, meaning_de: 'Das Heer', sign: '師', unicode: '䷆' },
  { sequence: '000010', number: 8, meaning_de: 'Das Zusammenhalten', sign: '比', unicode: '䷇' },
  { sequence: '111011', number: 9, meaning_de: 'Des Kleinen Zähmungskraft', sign: '小畜', unicode: '䷈' },
  { sequence: '110111', number: 10, meaning_de: 'Das Auftreten', sign: '履', unicode: '䷉' },
  { sequence: '111000', number: 11, meaning_de: 'Der Friede', sign: '泰', unicode: '䷊' },
  { sequence: '000111', number: 12, meaning_de: 'Die Stockung', sign: '否', unicode: '䷋' },
  { sequence: '101111', number: 13, meaning_de: 'Gemeinschaft mit Menschen', sign: '同人', unicode: '䷌' },
  { sequence: '111101', number: 14, meaning_de: 'Der Besitz von Großem', sign: '大有', unicode: '䷍' },
  { sequence: '001000', number: 15, meaning_de: 'Die Bescheidenheit', sign: '謙', unicode: '䷎' },
  { sequence: '000100', number: 16, meaning_de: 'Die Begeisterung', sign: '豫', unicode: '䷏' },
  { sequence: '100110', number: 17, meaning_de: 'Die Nachfolge', sign: '隨', unicode: '䷐' },
  { sequence: '011001', number: 18, meaning_de: 'Die Arbeit am Verdorbenen', sign: '蠱', unicode: '䷑' },
  { sequence: '110000', number: 19, meaning_de: 'Die Annäherung', sign: '臨', unicode: '䷒' },
  { sequence: '000011', number: 20, meaning_de: 'Die Betrachtung', sign: '觀', unicode: '䷓' },
  { sequence: '100101', number: 21, meaning_de: 'Das Durchbeißen', sign: '噬嗑', unicode: '䷔' },
  { sequence: '101001', number: 22, meaning_de: 'Die Anmut', sign: '賁', unicode: '䷕' },
  { sequence: '000001', number: 23, meaning_de: 'Die Zersplitterung', sign: '剝', unicode: '䷖' },
  { sequence: '100000', number: 24, meaning_de: 'Die Wendezeit', sign: '復', unicode: '䷗' },
  { sequence: '100111', number: 25, meaning_de: 'Die Unschuld', sign: '無妄', unicode: '䷘' },
  { sequence: '111001', number: 26, meaning_de: 'Des Großen Zähmungskraft', sign: '大畜', unicode: '䷙' },
  { sequence: '100001', number: 27, meaning_de: 'Die Ernährung', sign: '頤', unicode: '䷚' },
  { sequence: '011110', number: 28, meaning_de: 'Des Großen Übergewicht', sign: '大過', unicode: '䷛' },
  { sequence: '010010', number: 29, meaning_de: 'Das Abgründige', sign: '坎', unicode: '䷜' },
  { sequence: '101101', number: 30, meaning_de: 'Das Feuer', sign: '離', unicode: '䷝' },
  { sequence: '001110', number: 31, meaning_de: 'Die Einwirkung', sign: '咸', unicode: '䷞' },
  { sequence: '011100', number: 32, meaning_de: 'Die Dauer', sign: '恆', unicode: '䷟' },
  { sequence: '001111', number: 33, meaning_de: 'Der Rückzug', sign: '遯', unicode: '䷠' },
  { sequence: '111100', number: 34, meaning_de: 'Des Großen Macht', sign: '大壯', unicode: '䷡' },
  { sequence: '000101', number: 35, meaning_de: 'Der Fortschritt', sign: '晉', unicode: '䷢' },
  { sequence: '101000', number: 36, meaning_de: 'Die Verfinsterung des Lichts', sign: '明夷', unicode: '䷣' },
  { sequence: '101011', number: 37, meaning_de: 'Die Sippe', sign: '家人', unicode: '䷤' },
  { sequence: '110101', number: 38, meaning_de: 'Der Gegensatz', sign: '睽', unicode: '䷥' },
  { sequence: '001010', number: 39, meaning_de: 'Das Hemmnis', sign: '蹇', unicode: '䷦' },
  { sequence: '010100', number: 40, meaning_de: 'Die Befreiung', sign: '解', unicode: '䷧' },
  { sequence: '110001', number: 41, meaning_de: 'Die Minderung', sign: '損', unicode: '䷨' },
  { sequence: '100011', number: 42, meaning_de: 'Die Mehrung', sign: '益', unicode: '䷩' },
  { sequence: '111110', number: 43, meaning_de: 'Der Durchbruch', sign: '夬', unicode: '䷪' },
  { sequence: '011111', number: 44, meaning_de: 'Das Entgegenkommen', sign: '姤', unicode: '䷫' },
  { sequence: '000110', number: 45, meaning_de: 'Die Sammlung', sign: '萃', unicode: '䷬' },
  { sequence: '011000', number: 46, meaning_de: 'Das Empordringen', sign: '升', unicode: '䷭' },
  { sequence: '010110', number: 47, meaning_de: 'Die Bedrängnis', sign: '困', unicode: '䷮' },
  { sequence: '011010', number: 48, meaning_de: 'Der Brunnen', sign: '井', unicode: '䷯' },
  { sequence: '101110', number: 49, meaning_de: 'Die Umwälzung', sign: '革', unicode: '䷰' },
  { sequence: '011101', number: 50, meaning_de: 'Der Tiegel', sign: '鼎', unicode: '䷱' },
  { sequence: '100100', number: 51, meaning_de: 'Das Erregende', sign: '震', unicode: '䷲' },
  { sequence: '001001', number: 52, meaning_de: 'Das Stillehalten', sign: '艮', unicode: '䷳' },
  { sequence: '001011', number: 53, meaning_de: 'Die Entwicklung', sign: '漸', unicode: '䷴' },
  { sequence: '110100', number: 54, meaning_de: 'Das heiratende Mädchen', sign: '歸妹', unicode: '䷵' },
  { sequence: '101100', number: 55, meaning_de: 'Die Fülle', sign: '豐', unicode: '䷶' },
  { sequence: '001101', number: 56, meaning_de: 'Der Wanderer', sign: '旅', unicode: '䷷' },
  { sequence: '011011', number: 57, meaning_de: 'Das Sanfte', sign: '巽', unicode: '䷸' },
  { sequence: '110110', number: 58, meaning_de: 'Das Heitere', sign: '兌', unicode: '䷹' },
  { sequence: '010011', number: 59, meaning_de: 'Die Auflösung', sign: '渙', unicode: '䷺' },
  { sequence: '110010', number: 60, meaning_de: 'Die Beschränkung', sign: '節', unicode: '䷻' },
  { sequence: '110011', number: 61, meaning_de: 'Innere Wahrheit', sign: '中孚', unicode: '䷼' },
  { sequence: '001100', number: 62, meaning_de: 'Des Kleinen Übergewicht', sign: '小過', unicode: '䷽' },
  { sequence: '101010', number: 63, meaning_de: 'Nach der Vollendung', sign: '既濟', unicode: '䷾' },
  { sequence: '010101', number: 64, meaning_de: 'Vor der Vollendung', sign: '未濟', unicode: '䷿' },
]
